// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iawmktiqrarqqhwldjpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlhd21rdGlxcmFycXFod2xkanBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5ODk5ODUsImV4cCI6MjA2MzU2NTk4NX0.GpblbW9JFU-1S73hFU69VqCxVsZ0uATtp9dWA9lsrwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);